### ISSUE TITLE
Consertar responsividade da seção 'contribuidores'

### ISSUE THREAD

**Issue by victorhsr** [victorhsr/CEEIGEF#2]

**Comment by pedroviniv** [comment]
Issue fechada nesse [commit](https://github.com/victorhsr/CEEIGEF/commit/1ca78b90d74b601c04ada25f89140a3c878a9501)

**Comment by pedroviniv** [comment]
Issue fechada neste [commit](https://github.com/victorhsr/CEEIGEF/commit/1ca78b90d74b601c04ada25f89140a3c878a9501)
